export const ProjectData2 = [
    {
        no: 4,
        title: `Venkatramana's`,
        path: '/projects',
        img: ['./../images/P4/1.jpg', './../images/P4/2.jpg', './../images/P4/3.jpg', './../images/P4/4.jpg', './../images/P4/5.jpg', './../images/P4/6.jpg', './../images/P4/7.jpg', './../images/P4/8.jpg', './../images/P4/9.jpg', './../images/P4/10.jpg', './../images/P4/11.jpg', './../images/P4/12.jpg', './../images/P4/13.jpg', './../images/P4/14.jpg', './../images/P4/15.jpg', './../images/P4/16.jpg'],
        owner: 'Venkatraman',
        sdate: '444',
        cdate: 'June, 2022',
        location: 'Risinia Trendilla, Bachupally, Hyderabad, Telangana',
        area: '1300 sqft.',
        category: 'Residential Interiors',
        head: 'Scandinavian',
        desc1: 'Design & Execution',
        desc2: 'd desc 2',
    },
    {
        no: 5,
        title: `Sridhar's`,
        path: '/projects',
        img: ['./../images/P5/1.jpg', './../images/P5/2.jpg', './../images/P5/3.jpg', './../images/P5/4.jpg', './../images/P5/5.jpg', './../images/P5/6.jpg', './../images/P5/7.jpg', './../images/P5/8.jpg', './../images/P5/9.jpg', './../images/P5/10.jpg', './../images/P5/11.jpg', './../images/P5/12.jpg', './../images/P5/13.jpg', './../images/P5/14.jpg', './../images/P5/15.jpg', './../images/P5/16.jpg'],
        owner: 'Sridhar',
        sdate: '555',
        cdate: 'Aug, 2022',
        location: 'Risinia Trendilla, Bachupally, Hyderabad, Telangana',
        area: '1800 sqft.',
        category: 'Residential Interiors',
        head: 'Scandinavian',
        desc1: 'Design & Execution',
        desc2: 'e desc 2',
    },
    {
        no: 6,
        title: `Shridhar Malini's`,
        path: '/projects',
        img: ['./../images/P6/1.jpg', './../images/P6/2.jpg', './../images/P6/3.jpg', './../images/P6/4.jpg', './../images/P6/5.jpg', './../images/P6/6.jpg', './../images/P6/7.jpg', './../images/P6/8.jpg', './../images/P6/9.jpg', './../images/P6/10.jpg', './../images/P6/11.jpg', './../images/P6/12.jpg', './../images/P6/13.jpg', './../images/P6/14.jpg', './../images/P6/15.jpg', './../images/P6/16.jpg'],
        owner: 'Shridhar Malini',
        sdate: '666',
        cdate: 'Oct, 2022',
        location: 'Secunderabad, Telangana',
        area: '_',
        category: 'Elevation Design',
        head: 'Indo Westren',
        desc1: 'Design',
        desc2: 'f desc 2',
    },
];
