export const ProjectData = [
    {
        no: 1,
        title: `Nalini's`,
        path: '/projects',
        img: ['./../images/P1/1.jpg', './../images/P1/2.jpg', './../images/P1/3.jpg', './../images/P1/4.jpg', './../images/P1/5.jpg', './../images/P1/6.jpg', './../images/P1/7.jpg', './../images/P1/8.jpg', './../images/P1/9.jpg', './../images/P1/10.jpg', './../images/P1/11.jpg', './../images/P1/12.jpg', './../images/P1/13.jpg', './../images/P1/14.jpg', './../images/P1/15.jpg', './../images/P1/16.jpg'],
        owner: 'Nalini',
        sdate: '111',
        cdate: 'Aug, 2020',
        location: 'Bowenpally, Secunderabad, Telangana',
        area: '1250 sqft.',
        category: 'Residential Interiors',
        head: 'Use of wood Grains',
        desc1: 'Design',
        desc2: 'a desc 2',

    },
    {
        no: 2,
        title: `Vamsi's`,
        path: '/projects',
        img: ['./../images/P2/1.jpg', './../images/P2/2.jpg', './../images/P2/3.jpg', './../images/P2/4.jpg', './../images/P2/5.jpg', './../images/P2/6.jpg', './../images/P2/7.jpg', './../images/P2/8.jpg', './../images/P2/9.jpg', './../images/P2/10.jpg', './../images/P2/11.jpg', './../images/P2/12.jpg', './../images/P2/13.jpg', './../images/P2/14.jpg', './../images/P2/15.jpg', './../images/P2/16.jpg'],
        owner: 'Vamsi',
        sdate: '222',
        cdate: 'Sept 2021',
        location: 'Jasmine County, Gachibowli, Hyderabad, Telangana',
        area: '1550 sqft.',
        category: 'Residential Interiors',
        head: 'Contemporary',
        desc1: 'Design & Execution',
        desc2: 'b desc 2',

    },
    {
        no: 3,
        title: `Venkatesh Gowd's`,
        path: '/projects',
        img: ['./../images/P3/1.jpg', './../images/P3/2.jpg', './../images/P3/3.jpg', './../images/P3/4.jpg', './../images/P3/5.jpg', './../images/P3/6.jpg', './../images/P3/7.jpg', './../images/P3/8.jpg', './../images/P3/9.jpg', './../images/P3/10.jpg', './../images/P3/11.jpg', './../images/P3/12.jpg', './../images/P3/13.jpg', './../images/P3/14.jpg', './../images/P3/15.jpg', './../images/P3/16.jpg'],
        owner: 'Venkatesh Gowd',
        sdate: '333',
        cdate: 'Nov, 2020',
        location: 'Manikonda, Hyderabad, Telangana',
        area: '_',
        category: 'Elevation design',
        head: 'cc hh',
        desc1: 'Design',
        desc2: 'c desc 2',

    },
];
